language: go

sudo: false

go:
  - "1.15"
  - "1.16"
  - "1.17"
  - tip

before_install:
  - go get -t -v ./...

script:
  - sh coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
